const info = [
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Arctic Greening Driven By Warmer Temperatures',
        link: 'https://youtu.be/htzq2QbTKtw',
        picture: require('../assets/Images/1.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title:
            'NASA Sees High Temperatures, Wildfires, Sea Ice Minimum Extent in Warming Arctic',
        link: 'https://youtu.be/vtM9KTVGFVw',
        picture: require('../assets/Images/2.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Satellites See Fires Burning Across California',
        link: 'https://youtu.be/NR0fXlZ096Q',
        picture: require('../assets/Images/3.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title:
            'GLOBE Observer Getting Started: Mosquito Habitat Mapper - Sample Collection',
        link: 'https://youtu.be/KSeAA0IgS2w',
        picture: require('../assets/Images/4.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: `NASA Explores Earth's Magnetic 'Dent'`,
        link: 'https://youtu.be/qpdQcw_52iM',
        picture: require('../assets/Images/5.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: '5 Things That Changed Weather Forecasting Forever',
        link: 'https://youtu.be/_L-mGKFx0A4',
        picture: require('../assets/Images/6.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: `Greenland's Extreme Melt, 1 Year Later`,
        link: 'https://youtu.be/FSEQfgYBzKk',
        picture: require('../assets/Images/7.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'NASA Captures Isaias Twice Along East Coast',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/8.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Satellites See Hurricanes Douglas, Hanna',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/9.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Landsat 9: Continuing the Legacy Promo',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/10.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'PACE: Persistence and Perseverance Despite Pandemic',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/11.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'NASA Laser, ESA Radar Sync Up for Sea Ice',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/12.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Flying Alaska’s Glaciers with Operation IceBridge',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/13.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: `NASA Satellites Help Farmers in Central America's Dry Corridor`,
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/14.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Satellites See Saharan Dust from Space',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/15.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'NASA Tracks the Arizona Bush Fire',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/16.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Eyes in the Sky',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/17.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'NASA Ocean Ecosystem Mission Ready to Make Waves',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/18.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: 'Snow Scientists Dig Deep in Grand Mesa',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/19.png'),
    },
    {
        screen: 'Videos',
        text: 'By NASA',
        title: '40 Years of Watching Mount St. Helens',
        link: 'https://youtu.be/Anpgo2zknnQ',
        picture: require('../assets/Images/20.png'),
    },
];

export default info;

// data sourced from https://history.nasa.gov/SpaceApps2020.html
